server:
  port: 19099

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
