server:
  port: 19091

spring:
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:19092
          predicates:
            - Path=/user/**
        - id: order-service
          uri: http://localhost:19093
          predicates:
            - Path=/order/**
        - id: company-service
          uri: http://localhost:19094
          predicates:
            - Path=/company/**
        - id: delivery-service
          uri: http://localhost:19095
          predicates:
            - Path=/delivery/**, /deliveryroute/**
        - id: delivery-manager-service
          uri: http://localhost:19096
          predicates:
            - Path=/deliverymanager/**
        - id: ai-service
          uri: http://localhost:19097
          predicates:
            - Path=/ai/**
        - id: slack-service
          uri: http://localhost:19098
          predicates:
            - Path=/slack/**
        - id: product-service
          uri: http://localhost:19099
          predicates:
            - Path=/product/**

jwt:
  secret:
    key: 2e2ab37ae96a148bcb9919d74ecbd818ce9c097151c4b5d5d9049bcbdc05d349c59b9e1ad762c7b6ccf8b73e79fef4a82d13f08db22ca3c3070705b08df3f41c

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/