server:
  port: 19097
spring:
  application:
    name: ai-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics
    driver-class-name: org.postgresql.Driver
    username: postgre
    password: postgre
    hikari:
      maximum-pool-size: 4
  data:
    redis:
      host: localhost  # Redis 서버의 호스트명
      port: 6379       # Redis 서버 포트
      username: default
      password: systempass
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

gemini-baseurl: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent"