#server:
#  port: 19091

spring:
  application:
    name: slack
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
  slack:
    api-url: "https://slack.com/api/chat.postMessage"
    user-list-url: "https://slack.com/api/users.list"

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka
